name: vfsclient
description: A VFS client SDK.
version: 1.0.0
repository: https://github.com/cubetiq/vfsclient-sdk-dart.git

environment:
  sdk: ^3.3.1

dependencies:
  http: ^1.2.1
  logger: ^2.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
